### ISSUE TITLE
There is a bug please fix this

### ISSUE THREAD

**Issue by smartnavdeep** [Ved-programmer/Login-System#16]
Hi Ved

I got an error like this...

![Screenshot 2020-10-10 112726](https://user-images.githubusercontent.com/65970997/95647636-9c8e5580-0aee-11eb-9e3d-67217bfb72ff.png)

Hope you will fix it

**Comment by Ved-programmer** [comment]
Hmm. I have made a change, in which I have added the delete account feature and also fixed the bug. If you get another bug like this or this continues to happen then please let me know. I would need some more details if this continues to happen

**Comment by smartnavdeep** [comment]
OK, so now I'm closing this issue
