### ISSUE TITLE
Couple more errors

### ISSUE THREAD

**Issue by smartnavdeep** [Ved-programmer/Login-System#17]
Hi Ved, I actually saw some more errors while running the code, here are those screenshots..
Error Number one : A Set of characters appear in the terminal when the application is a gui.
![Screenshot 2020-10-12 190912](https://user-images.githubusercontent.com/65970997/95753212-e6c63100-0cbe-11eb-969e-afc813f8a4af.png)
Error Number 2 When I tried entering the invalid character "\"
Actually you said that only a certain characters are valid, but as I'm testing the code, I had to enter the characters which are not valid also, such as "\" symbol. The program should at least raise an exception error. However this could be fixed.
Here is how you can fix this :

Actually in python, symbol "\" is a special symbol, which is used to represent ascii letters and special strings
In order to prevent that you need to add a 'r' or escape them in front of any input box etc.

Error Number 3

![Screenshot 2020-10-10 112726](https://user-images.githubusercontent.com/65970997/95754517-cb5c2580-0cc0-11eb-9dc0-40b2c30cf2e8.png)

Actually I don't this, please see it

**Comment by Ved-programmer** [comment]
for the first error there is just a print statement in the hashing file which I can remove easily. As per for the second error, can you give me the string(the password that you entered). also, I am not sure if you found this bug in the latest code, as I have must a bracket in the "i + 1" line. The line is - "else:final += 2 * length + length // (i + 1)" and it is line number 24. If the error continues then please let me know.

**Comment by Ved-programmer** [comment]
This first error is fixed now, can you please check if the second and the third error is fixed?

**Comment by Ved-programmer** [comment]
The sooner you tell me the better, also make sure that you are running the latest version of the code

**Comment by Ved-programmer** [comment]
Great,  I have fixes the errors, I will update the repository tomorrow just so because I want to do some checks that the updated version as expected. Now I am closing the issue. Please create another issue if you still find more bugs in the updated version(tomorrow)
