### ISSUE TITLE
Need to Define what is this repo for.

### ISSUE THREAD

**Issue by smartnavdeep** [Ved-programmer/Login-System#18]
Hi Ved,
Actually the first time I visited I thought that this was a kind of password saver, where we can login in and save our passwords.
But I later learnt that this is a login system.
We have already mentioned in the documentation that this is a login system but we didn't mention that how to make use of this repo.

Actually here is what I thought and wrote in my fork :
![Screenshot 2020-10-17 200429](https://user-images.githubusercontent.com/65970997/96339745-13f65300-10b4-11eb-91ac-44e845969d5d.png)

So please tell me that is what I thought and wrote in my fork was correct or wrong and if it was wrong please tell that what shoul I write.
And I already have everything done everything in my the [forked repo](https://github.com/smartnavdeep/Login-System) so please tell me when you are ready and I will create a pull request

Regards,
[Navdeep](https://github.com/smartnavdeep)

Edit : If I did say anything bad by mistakenly, then I'm sorry for that

**Comment by Ved-programmer** [comment]
No, you did not say anything bad, actually originally I was also planning to make it a password saver but it turned into a log-in system. After doing everything for the login system part, I will make it a full password saver. Uptil now it is a login system. But about after a month or two. It will start to become a password saver.

**Comment by Ved-programmer** [comment]
So I suggest not to make this change to the documentation.

**Comment by Ved-programmer** [comment]
Actually, this is indeed just a Log In system however, I could change to be something else later, and also many projects don't have meaning, they are just for fun. I think that we should let the documentation be as it is. Also, I think that we have done enough for a log in system. I might still be making contributions but not as often as I have been. You could also move to other repositories or help me in my new projects.

**Comment by smartnavdeep** [comment]
Oh, I see.
