### ISSUE TITLE
Adding licence

### ISSUE THREAD

**Issue by smartnavdeep** [Ved-programmer/Login-System#2]
Hi Ved, i think we need to add a licence to your project according to github's recommended community standards.([referred here](https://github.com/Ved-programmer/Login-System/community))

Please tell me if you don't have an idea of adding a licence, just wanted to contribute to this project

Regards,
Navdeep

**Comment by Ved-programmer** [comment]
No I don't have knowledge regarding license. Do whatever you think is right. I will study about licenses and then see what you have done by tomorrow evening
