### ISSUE TITLE
Fuck you!

### ISSUE THREAD

**Issue by iamabastard** [Ved-programmer/Login-System#26]
# 🖕🖕🖕🖕🖕🖕🖕🖕

![fuck off](https://i85.photobucket.com/albums/k59/rockstarr_02/Nate_Zipline.gif)

**Comment by smartnavdeep** [comment]
Look G**Lord you shouldn't be doing this !

**Comment by iamabastard** [comment]
Fuck off you little brat !!!

**Comment by smartnavdeep** [comment]
😭😭

**Comment by smartnavdeep** [comment]
@Ved-programmer please look at the guy he is creating  nuisance

**Comment by smartnavdeep** [comment]
Look G**Lord close all this now or we will complain github !

**Comment by iamabastard** [comment]
Fuck off

**Comment by iamabastard** [comment]
Fuck Off

**Comment by iamabastard** [comment]
Fuck off

**Comment by Natalia-Katie** [comment]
Looking you don't have rights do this !! This is violence against children !!

**Comment by smartnavdeep** [comment]
yeah !! @Ved-programmer  Why aren't you doing anything ??

**Comment by iamabastard** [comment]
huh two 💘 birds

**Comment by Natalia-Katie** [comment]
we are just friends ! anyways navdeep can't we stop him ?

**Comment by smartnavdeep** [comment]
only Ved or this guy can stop it, Ved can even block this guy so that he won't be able to do anything

**Comment by iamabastard** [comment]
![..](https://i85.photobucket.com/albums/k59/rockstarr_02/Nate_Zipline.gif)

**Comment by iamabastard** [comment]
# Natalia 💘 Navdeep

**Comment by smartnavdeep** [comment]
ved where are you !

**Comment by smartnavdeep** [comment]
Look I and Natalia are just friends

**Comment by iamabastard** [comment]
Shut up you punk, you are still a little fucking brat !!

**Comment by smartnavdeep** [comment]
😭😭 it is useless to be here Ved and GitHub will see want needs to be settled

**Comment by Natalia-Katie** [comment]
yeah he is going against the law, this will be counted under COPPA, GitHub Will see him 😭😭

**Comment by iamabastard** [comment]
WTF you two 💋💘💋birds are leaving  ?

**Comment by iamabastard** [comment]
Hey Ved Where The Fuck are you ?

**Comment by iamabastard** [comment]
Come out you freaking, fucking brat !

**Comment by iamabastard** [comment]
are you scared ??

**Comment by iamabastard** [comment]
take this...

**Comment by iamabastard** [comment]
![..](https://i85.photobucket.com/albums/k59/rockstarr_02/Nate_Zipline.gif)

**Comment by Natalia-Katie** [comment]
We have reported it to GitHub, so you won't have to worry now 

#😛

**Comment by Ved-programmer** [comment]
Ok, Ok, Ok. I just had a look at all this right now.

**Comment by Ved-programmer** [comment]
I'll do something about it.

**Comment by Ved-programmer** [comment]
Dude, delete everything and apologize and you can be free else their is the more disturbing option. You pick which one you want. I wouldn't have reporting this to github and blocking you.
