### ISSUE TITLE
By mistake, I created a repository inside the repository, how am I supposed to delete that? All I want to do is to delete the respository inside the repository with the code

### ISSUE THREAD

**Issue by Ved-programmer** [Ved-programmer/Login-System#4]
Can you delete that for me?

**Comment by smartnavdeep** [comment]
OK

**Comment by smartnavdeep** [comment]
I have made a pull request and I also have a collaborator access to your repo, so I can merge it.

**Comment by smartnavdeep** [comment]
I have made a pull request, please merge it and yeah before merging it, please check that did i deleted it correctly

**Comment by smartnavdeep** [comment]
Actually I don't have write access to your repo, that's why I need to fork your repo and pull request

**Comment by smartnavdeep** [comment]
I'm still making those pull request

**Comment by smartnavdeep** [comment]
Done, all you need to do is that you need to preview the changes and push the request to your repo

**Comment by smartnavdeep** [comment]
Ved, there is a pull request named 'Deleted Repo.repo' only accept that

**Comment by smartnavdeep** [comment]
Wait ! don't merge any thing!

**Comment by Ved-programmer** [comment]
ok

**Comment by Ved-programmer** [comment]
I am waiting

**Comment by Ved-programmer** [comment]
I can't see any pull request of Deleted Repo.repo

**Comment by smartnavdeep** [comment]
I'm still creating it, hold on please

**Comment by Ved-programmer** [comment]
fine

**Comment by smartnavdeep** [comment]
Check now

**Comment by Ved-programmer** [comment]
ya, it worked

**Comment by smartnavdeep** [comment]
Is everything ok now

**Comment by smartnavdeep** [comment]
Happy to hear it : )

**Comment by smartnavdeep** [comment]
Please close this issue
